### ISSUE TITLE
 get_loader ??

### ISSUE THREAD

**Issue by zhangyiming1** [Epiphqny/Multiple-instance-learning#1]
非常感谢你能提供这些代码，我在参考你的代码的时候，没有找到 get_loader，请问你能方便提供吗？我想知道这一块是怎么处理的？非常感谢你！

**Comment by YuqingWang1029** [comment]
> 非常感谢你能提供这些代码，我在参考你的代码的时候，没有找到 get_loader，请问你能方便提供吗？我想知道这一块是怎么处理的？非常感谢你！

可以参考https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/data_loader.py 的 data_loader 和 build_vocab ,如果觉得代码不错的话请点个赞再走，O(∩_∩)O谢谢
