### ISSUE TITLE
关于《CNN-RNN: A Unified Framework for Multi-label Image Classification》

### ISSUE THREAD

**Issue by mymuli** [Epiphqny/Multiple-instance-learning#3]
请问一下，关于这篇论文的实验，你实现了吗？
在train.py里面，默认有data/zh_vocab.pkl，data/resized2014，data/annotations/img_tag.txt，而我没有见到这些文件....
请问一下，去哪里下载这些文件呢？

**Comment by YuqingWang1029** [comment]
这个是我们自己的数据构造的,不便公开哈～zh_voacb是词汇表，resized2014是图像数据集，img_tag.txt存的图像和标签的映射对

Rmuli <notifications@github.com>于2019年4月8日 周一上午9:13写道：

**Comment by mymuli** [comment]
请问一下，zh_voacb-词汇表，是怎么构造的？谢谢....

**Comment by YuqingWang1029** [comment]
> 请问一下，zh_voacb-词汇表，是怎么构造的？谢谢....

可以参考https://github.com/Epiphqny/Multiple-instance-learning/blob/master/data_process/build_vocab.py 的代码

**Comment by mymuli** [comment]
我想在自己的数据集上实现一下...zh_voacb和img_tag.txt怎么构建，我还是一头雾水...我能加你微信，讨论一下吗？...十分感谢！

**Comment by YuqingWang1029** [comment]
> 我想在自己的数据集上实现一下...zh_voacb和img_tag.txt怎么构建，我还是一头雾水...我能加你微信，讨论一下吗？...十分感谢！
