### ISSUE TITLE
CNN rnn

### ISSUE THREAD

**Issue by nisnab** [Epiphqny/Multiple-instance-learning#4]
I would like to ask if u have implemented CNN:RNN completely and what were your findings. I  would like to know, if the two .py files are the only thing essential. baSically, i would like to know about code structure.

**Comment by YuqingWang1029** [comment]
> I would like to ask if u have implemented CNN:RNN completely and what were your findings. I would like to know, if the two .py files are the only thing essential. baSically, i would like to know about code structure.

I just implemented the basic cnn and rnn structure, without more details in the paper. Also, the data_process folder is used in this model. I have not done more deep research in this paper.

**Comment by nisnab** [comment]
ok, thank you for such a quick response
