### ISSUE TITLE
What does the hard coding parameter 1032 mean in visual concept ?

### ISSUE THREAD

**Issue by zaynmi** [Epiphqny/Multiple-instance-learning#6]
I'm trying to implement visual concept on my own dataset. I have generated img_tag.txt by myself and zh_vocab.pkl by using build_vocab.py. Then I tried to run train_visual.py, I got an error when computing BCE loss
```
Traceback (most recent call last):
  File "/home/tang/Multiple-instance-learning/visual_concept/train_visual.py", line 133, in <module>
    main(args)
  File "/home/tang/Multiple-instance-learning/visual_concept/train_visual.py", line 91, in main
    pos=nn.functional.binary_cross_entropy(outputs*targets,targets)*1e3
RuntimeError: The size of tensor a (1032) must match the size of tensor b (6) at non-singleton dimension 1
```
The outputs size is [256(batchsize), 1032], and my targets size  is [256, 6], where 6 is the max length of tags in a batch
Then I found out that there is a hard coding parameter 1032 in data_process/one_hot.py which you didn't use. So I'm wondering is 1032 related to vocabulary size of your dataset ?

**Comment by YuqingWang1029** [comment]
> vocabulary size


> I'm trying to implement visual concept on my own dataset. I have generated img_tag.txt by myself and zh_vocab.pkl by using build_vocab.py. Then I tried to run train_visual.py, I got an error when computing BCE loss
> 
> ```
> Traceback (most recent call last):
>   File "/home/tang/Multiple-instance-learning/visual_concept/train_visual.py", line 133, in <module>
>     main(args)
>   File "/home/tang/Multiple-instance-learning/visual_concept/train_visual.py", line 91, in main
>     pos=nn.functional.binary_cross_entropy(outputs*targets,targets)*1e3
> RuntimeError: The size of tensor a (1032) must match the size of tensor b (6) at non-singleton dimension 1
> ```
> 
> The outputs size is [256(batchsize), 1032], and my targets size is [256, 6], where 6 is the max length of tags in a batch
> Then I found out that there is a hard coding parameter 1032 in data_process/one_hot.py which you didn't use. So I'm wondering is 1032 related to vocabulary size of your dataset ?

yes, you are right, the 1032 is the vocabulary size.

**Comment by zaynmi** [comment]
谢谢您的回复，我还是有个疑问，
```
        for i, (images, targets, lengths) in enumerate(data_loader):
            # Set mini-batch dataset
            images = images.cuda()
            targets = targets.cuda()
            
            #targets = pack_padded_sequence(captions, lengths, batch_first=True)[0]
     
            # Forward, backward and optimize
            features = encoder(images)
            outputs = decoder(features)
```
若按照https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/data_loader.py 的 data_loader ，那么 ` for i, (images, targets, lengths) in enumerate(data_loader):` 得到的targets的shape是[batch_size, max_length]， 但是outputs的shape是[batch_size, vocab_size], 下述的`outputs*targets` 是怎么做到的？
```
pos=nn.functional.binary_cross_entropy(outputs*targets,targets)*1e3
neg=nn.functional.binary_cross_entropy(outputs*(1-targets)+targets,targets)*1
```

**Comment by YuqingWang1029** [comment]
> 谢谢您的回复，我还是有个疑问，
> 
> ```
>         for i, (images, targets, lengths) in enumerate(data_loader):
>             # Set mini-batch dataset
>             images = images.cuda()
>             targets = targets.cuda()
>             
>             #targets = pack_padded_sequence(captions, lengths, batch_first=True)[0]
>      
>             # Forward, backward and optimize
>             features = encoder(images)
>             outputs = decoder(features)
> ```
> 
> 若按照https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/data_loader.py 的 data_loader ，那么 ` for i, (images, targets, lengths) in enumerate(data_loader):` 得到的targets的shape是[batch_size, max_length]， 但是outputs的shape是[batch_size, vocab_size], 下述的`outputs*targets` 是怎么做到的？
> 
> ```
> pos=nn.functional.binary_cross_entropy(outputs*targets,targets)*1e3
> neg=nn.functional.binary_cross_entropy(outputs*(1-targets)+targets,targets)*1
> ```

The time is so long that i can not remember all the details, but i think you should embed the target to vocab space, perhaps you could refer to https://github.com/Epiphqny/Multiple-instance-learning/blob/master/data_process/one_hot.py, also maybe you need to change the number -1 in this file to other numbers according to the training file, based on the loss function
